### ISSUE TITLE
Feature request: React DevTools integration

### ISSUE THREAD

**Issue by bvaughn** [codesandbox/sandpack#153]
How would you feel about adding (opt-in) React DevTools support to Sandpack?

Integrating React DevTools into Code Sandbox seems like a pretty big win for users. Could Sandpack benefit in a similar way?

I'm thinking about this problem space in the context of the [new React JS documentation](https://beta.reactjs.org/) and how it would be nice to introduce DevTools along with some of the React concepts we're featuring.

Would someone on the Code Sandbox side be interested in talking about this? (Or even just reviewing a PR if I were submit one?)

**Comment by danilowoz** [comment]
Hey @bvaughn, sorry for the late answer, I might've missed the notification somehow.

It would be amazing if we could make this work, for sure! I was thinking of creating a new component on Sandpack that would render the React DevTool, by this way we can leave it for the user to decide where and how to render it.

I'm going to prioritize this internally and let you know when we have some news about it. Unfortunately, I think you will not able to do this on your own, due to some internal conditional on our bundler that blocks the DevTools dependency to be fetched, in order to reduce the amount of dependency in the iframe. 

Thanks for raising this up!

**Comment by bvaughn** [comment]
No worries, @danilowoz. I’m looking forward to seeing what you come up with. Please let me know if I can help.

**Comment by danilowoz** [comment]
Done on https://sandpack.codesandbox.io/docs/advanced-usage/components#reactdevtools

**Comment by bvaughn** [comment]
Thank you !
