### ISSUE TITLE
Feature request: vim keybindings

### ISSUE THREAD

**Issue by jsjoeio** [codesandbox/sandpack#280]
# Tell us how you think we can improve Sandpack

It would be cool to see vim keybindigns

## Packages affected

- [x] sandpack-client
- [ ] sandpack-react

## What is this feature?

Vim keybindings

## How would your idea work?

It would allow you to use Vim

## Do you have any examples of how you would like to see us implement it?

Here is how replit does it for Codemirror: https://github.com/replit/codemirror-vim

**Comment by danilowoz** [comment]
Hey @jsjoeio, thanks for raising this issue, indeed it would be very cool to use more extensions in the code editor component. That's why we addressed this option in https://github.com/codesandbox/sandpack/pull/286, which aims to support any Codemirror@6 extension.

I hope it solves your problems, feel free to leave any feedback in the PR.

**Comment by jsjoeio** [comment]
Hooray! Can't wait to try this out. Thanks again @danilowoz 🙌
