### ISSUE TITLE
`Files` Object API: Allow user to pass reference to file in their file system

### ISSUE THREAD

**Issue by cliffordfajardo** [codesandbox/sandpack#435]
# Tell us how you think we can improve Sandpack

## Packages affected
-   [X] sandpack-client
-   [X] sandpack-react

## What is this feature?
 _Firstly, I really like sandpack's API allowing you to pass a simple string to as the code source file I think this should remain & im not implying we shouldn't have it; with that. said:_

Perhaps supplementary option for passing the contents of a file would be allowing the user to pass a path that's in their file system, which under the hood would use the [File API](http://dev.w3.org/2006/webapi/FileAPI/) proposed as a standard and [implemented in most browsers](http://caniuse.com/#feat=fileapi). The [filesystem API](https://web.dev/file-system-access/) is newer and I have not look into it as much, but it might be useful here too

## Motivation
- keep  source code that I pass to `<Sandpack>` in a regular file, instead of keeping the source of truth in a string;
- 1 source of truth, currently I have the file in my file system and then what I end up doing is pasting the contents of that file in another file that exports the string. Its easy for these 2 files to go out of sync when making modifications;  there have been several time where I have been editing a long file and forgot to update the string containing my app code. 
	```js
	/*******************add.js*******************/
	export function add(a,b) {return a + b}

	/*******************add-template.js*******************/
	// copy file contents ^^
	export const file = `
	export function add(a,b) {return a + b}
	`
	```
For example,  is a recent real sandpack example that I was working on which has the duplication I mentioned: https://codesandbox.io/s/react-reconciler-bug-forked-ijy418?file=/src/Glossary/examples/HelloReactReconciler/index.tsx

## How would your idea work?
TODO: I need to play around with the `File` system API
But would also like to hear codesandbox team's thought on this; perhaps there is a strong reason for why this may not be feasible and I'm likely missing context.

**Comment by danilowoz** [comment]
Hey, I don't think I have the whole context about the decisions that were made in the past. But based on the all information I have, I believe it's an issue that the consumer application needs to deal with. Because the general purpose of Sandpack is just to provide a lightweight interface between the CodeSandbox bundler and a frontend application, and not provide an opinionated way to consume files or something (although we can make the life easier for everyone), because Sandpack doesn't know how you're going to bundle your application or how you're going to load it.

So, that said, you can easily consume local files using webpack loaders (or even [Parcel](https://parceljs.org/features/bundle-inlining/#inlining-a-bundle-as-text)), for example: 

```jsx
import { Sandpack } from "@codesandbox/sandpack-react";

import codeString from "!!raw-loader!./example";

export default function App() {
  return <Sandpack template="react" files={{ "/App.js": codeString }} />;
}
```

https://codesandbox.io/s/raw-files-ievlg?file=/src/App.js

Does it make sense? Curious to know if it solves your problem

Thanks again for all details you put in this issue and for the feedback ❤️

**Comment by danilowoz** [comment]
@cliffordfajardo the previous comment makes sense for you? I'm curious to know if that solves your issue, and we can close it.

**Comment by cliffordfajardo** [comment]
Makes sense - thanks!
Will close
