### ISSUE TITLE
Degraded editor performance during file compression

### ISSUE THREAD

**Issue by joebingham-wk** [codesandbox/sandpack#442]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

Hi! First off, thank you for this amazing tool 🙏  It has been an extremely simple process to get up and running with an embedded code editor, which is incredibly awesome.

The issue I noticed is that when using the [suggested strategy](https://github.com/codesandbox/sandpack/discussions/58) for using private NPM packages, I've noticed that if the package is large, it can cause a really notable lag when trying to use the editor (see the video below). From what I can tell, this happens because when the files change, it [kicks of a useEffect](https://github.com/codesandbox/sandpack/blob/b2308d30ff40d667c9632ebee70d1dddaec36744/sandpack-react/src/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx#L46-L67) that [compresses the files](https://github.com/codesandbox/codesandbox-importers/blob/7e0445c7ac833fbffd20bcb3c49c1d0af364ddea/packages/import-utils/src/api/define.ts#L11-L16). 

With smaller files, that makes a lot of sense and allows the ability to open in a codesandbox anytime with little delay, which is awesome. However, it seems that if this is the go-to strategy for using private packages, it may benefit from having a way to avoid this behavior for larger packages. The options I thought of were:
1. Add an option in the `options` or `customSetup` to remove the "Open in Codesandbox button"
1. Make the compression an asynchronous process that does not block the main thread (and a loader can show in the button till it's complete)
1. Implement a caching strategy to avoid re-compressing large files (maybe detect which file changed and only re-process them?)

I'm not familiar enough with the package to know which of these, if any, are viable, but option 1 seemed like it'd be relatively straight forward compared to the others.

https://user-images.githubusercontent.com/46691367/163629990-c00a8e2e-5109-423a-9f68-37ce532ce459.mov

(Apologies if the video is unclear, but anytime that typing stops, it's because it's lagging)

> Note: I tried running with `autorun: false` and `recompileMode: 'delayed'` to try to change the behavior, and they might have helped a little bit, but the issue persisted.

## What were you doing when the problem occurred?

Editing a file while using a very large UI library package as a dependency.

### What steps can we take to reproduce the problem?

- Use [this strategy](https://github.com/codesandbox/sandpack/discussions/58) to add in a LARGE custom package. Unfortunately mine is private or else I'd set up an example using it, but it's a 2.3MB bundle comprised of a relatively large UI component library.
- Attempt to edit a code file that imports that library

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |         0.15.2   |
| Sandpack-react version  |      0.15.2   |
| Browser                 |     chrome / 100.0.4896.88       |
| Operating System        |       macOS / 12.3.1       |

Apologies if this a duplicate issue or there's already an easy way to go about this!

**Comment by danilowoz** [comment]
Hey, @joebingham-wk thank you so much for all the details in this issue, it helped a lot! 🙌 

I see the problem, and I agree that it might become a burden for some specific cases. That said, I took some time to figure out how to solve it, and I'm going to use your suggestions as a reference:
1. **Add an option in the options:** actually `SandpackPreview` component already supports it, and it's straightforward to bring this option to the Sandpack component, addressed on https://github.com/codesandbox/sandpack/pull/443;
2. **Make it async:** unfortunately, turning this function async won't alleviate the main thread because the compress function is still synchronous. One possible solution would be to refactor `lz-string` and break the main operation into small tasks (wrapping them into `setTimeout`s to unblock the main thread). However, even doing this, I can't see the real benefits for the user because once the user has made a new change, we need to discard the current operation, which is progress. Very tricky; 
3. **Cache**: it would solve part of the problem if we could retrieve only the unchanged files from the cache and compress the file-changes into the previous string. But I don't think `lz-string` works like that, as we're compressing the whole string and not part of them (pretty sure it would cause some concatenation errors). Plus, we would introduce a cache strategy (more code & more memory usage) for most users who don't have this problem.

**Immediate solution:** hide the Open in CSB button, also I don't think you really want to export your private package to a public sandbox, right? 
```jsx
<Sandpack options={{ showOpenInCodeSandbox: false }} />
```

I'm not going to close this issue, as I'm very interested to know what you think about the technical challenges I mentioned above.

**Comment by DeMoorJasper** [comment]
> 2. **Make it async:** unfortunately, turning this function async won't alleviate the main thread because the compress function is still synchronous. One possible solution would be to refactor `lz-string` and break the main operation into small tasks (wrapping them into `setTimeout`s to unblock the main thread). However, even doing this, I can't see the real benefits for the user because once the user has made a new change, we need to discard the current operation, which is progress. Very tricky; 

We can run it in a webworker, that would make it async? This is probably a good change regardless as this isn't really something that should block the main thread

**Comment by joebingham-wk** [comment]
Hi @danilowoz! Thank you for getting a fix pushed out so quickly - I gave hiding the button a try to verify it worked on my end, and that solution works great for me 🎉 

All of your thoughts make a lot of sense to me. Especially because, as you mentioned, consumers like me wouldn't want the package exported to a public sandbox anyway, so creating a complicated mechanism of breaking up the work really doesn't make sense if it doesn't need to be published anyway. 

My proposed option 3 really doesn't make sense (I overlooked how `lz-string` was working), so nothing more to add there haha. Option 2 also seems more complicated than it's worth. The only thought I had there is, can a packaged dependency spawn a web worker? Even if it's possible, that may be a terrible idea for some reason, but theoretically it seems like it could work here to offload the compression in its entirety to the worker. It wouldn't address the discard problem and could get complicated fast, but at least the heaviest processing could be neatly siloed outside the concern of the UI.

All that being said, I agree option 1 is the way to go and only mention the web worker in case it's an option that can be helpful later. Thank you again for exposing that option!

**Comment by danilowoz** [comment]
Yeah, maybe a web worker could be a possible way to solve it, but I was wondering a few things:
- How much would cost the browser to keep multiple webworkers? or we could create only one and reuse it? 
- How to create a runtime webworker? Like, is it possible to create a webworker from a third package (Sandpack-react)?

@joebingham-wk let me know if you want to give it a try, otherwise, I'll prioritize it internally.

**Comment by DeMoorJasper** [comment]
Regarding web workers in npm modules, the only safe way I know of is to inline the contents of the webworker's bundle, this is how for example `js-untar` does it, but it's definitely possible to spin one up from a node module. We also only need one, as we can reuse it for all compressions, basically just turn the `lz-string` library into an async version that runs everything on a web worker.

I do remember a previous discussion about this a couple months back where even if we had proper support for it on larger sandboxes we eventually also reach the max length limit of a url, in which case we should probably use a post request (so maybe we can use that for larger sandboxes instead of web-workers?). I think this is the post request we should use? Not sure, haven't checked with the backend team: https://github.com/codesandbox/sandpack/blob/4e7e6683a6d06559bdc789ff07689387425bee9a/sandpack-client/src/client.ts#L319-L351

**Comment by danilowoz** [comment]
Awesome, so it looks possible.

About the URL reaches the limit, we fix it here: https://github.com/codesandbox/sandpack/blob/main/sandpack-react/src/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx#L89

**Comment by danilowoz** [comment]
Addressed here https://github.com/codesandbox/sandpack/issues/448

Thanks @joebingham-wk once again
