### ISSUE TITLE
how does the sandpack preview respect the local storage?

### ISSUE THREAD

**Issue by aboveyunhai** [codesandbox/sandpack#502]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

I change the color mode in localhost development and then refresh the production website, it also affects colormode in production sandpack, vice versa. 
may I consider it as a security issue?

the function I use in code: 
https://chakra-ui.com/docs/styled-system/features/color-mode#usecolormode

production: https://playground-ts.vercel.app/
repo: https://github.com/aboveyunhai/playground-ts

### What steps can we take to reproduce the problem?
![report](https://user-images.githubusercontent.com/35160613/174470290-8449e748-e921-4eb4-bcdc-2545574d5f71.gif)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |       latest       |
| Browser                 |     chrome         |
| Operating System        |     windows         |

**Comment by danilowoz** [comment]
Hey @aboveyunhai, it's expected behavior. Both pages (localhost and production) use the same URL in the iframe, which is rendered by Sandpack, so this means that they're share the same localstorage values: 
![Screenshot 2022-06-20 at 14 20 08](https://user-images.githubusercontent.com/4838076/174610750-21e9c59c-fb87-4c72-aa38-904f5a9b7f20.png)

Hope it helps
