### ISSUE TITLE
function not defined using vanilla template

### ISSUE THREAD

**Issue by bradwoods** [codesandbox/sandpack#509]
# Bug report

-   [ ] sandpack-client
-   [x] sandpack-react

Using the `vanilla template`. When attempting to call a function from the `.html` file that is defined in the `.js` file, a `function is not defined` error is shown.

[link](https://codesandbox.io/s/white-hooks-yy6l76?file=/src/App.tsx)

**Comment by danilowoz** [comment]
Hey, this's expected behavior on Sandpack. There are two main reasons why any file has access to the global scope:
- Sandpack can't pollute the global scope, because all the bundler scripts run in the same context. So, we wrap all the files into another function in order to prevent their content from mistakenly affecting bundler functionality;
- Sandpack needs to provide the right context for each file after its transpilation, so it wraps the file content into a Sandpack helper, which will execute the js file properly with the right context, for example:
```js
(function eval(require, global) {
  require("index.css") // originally import("index.css");

 // rest of the file
})
```

So, in order to have access to the `onClick` function at the window context, you need to expose it like this:

```js
function onClick() {
  console.log('click')
}

window.onClick
```

Hope it helps.

**Comment by bradwoods** [comment]
Thanks again!
