### ISSUE TITLE
Documentation: How to have editor and preview not be children of the same provider?

### ISSUE THREAD

**Issue by zaini** [codesandbox/sandpack#579]
Is it possible to have an editor and preview be linked together but not some the same provider? I don't need to use the React components and am happy to use sandpack-client, but I want it so that when I make changes in the editor, the preview updates.

I have multiple editors in one tab and multiple views in another tab and want to be able to control them.

I basically don't want both SandpackEditor and SandpackPreview to be in the same file or component. How can I do that? Even with sandpack-client, it's not clear how to separate the editor from the preview.

I have tried storing the files/code that the the preview renders in a state and then updating that state, but it doesn't cause the preview to rerender.

**Comment by danilowoz** [comment]
Hey @zaini, I'm afraid I didn't really get what's your problem.

Could you try to state it differently? I'm more curious about what you're trying to achieve instead of the problem you're facing on Sandpack. Maybe a diagram can help me to understand what component tree you want.

Feel free to DM me on Discord if it makes it easier for you.
