### ISSUE TITLE
Add support for decorators in SandpackCodeEditor

### ISSUE THREAD

**Issue by triptu** [codesandbox/sandpack#626]
# Tell us how you think we can improve Sandpack

Is it possible to add decorators for CodeEditor as well similar to the CodeViewer [decorators](https://sandpack.codesandbox.io/docs/advanced-usage/components#codemirror-decorations)? If there is any other way to highlight certain lines that would work as well. A hacky way I can think of is to use the fact that each line has `cm-line` in class. 

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Do you have any examples of how you would like to see us implement it?

The same interface as CodeViewer would be great.

**Comment by danilowoz** [comment]
Hey, currently, it's not possible via SandpackCodeEditor. 

We encourage using decorators only on read-only mode simply because it's static, and decorators will have fixed values. On the other hand, a regular code editor is dynamic and would require handling different use cases, like removing decorators and updating their position.

But I'm curious to know how you would use these decorators on a live code editor. Could you give some examples? Maybe there are some cases I'm not taking into account. 

If you're really interested in this feature, I will encourage trying to implement it by yourself using the following API: https://sandpack.codesandbox.io/docs/advanced-usage/components#extensions Plus, you can take some ideas from the original Sandpack implementation.

Hope it helps.

**Comment by triptu** [comment]
Ah! missed that in the doc. Thanks for pointing it out, extensions, and being able to grab the CodeMirror instance are both very helpful. We can close the issue.

As for the need, I'm trying to build a running tutorial broken into steps. So you set up the base in step1, add feature1 in step2, feature2 in step3, and so on. I want to highlight the difference in code between the subsequent steps clearly, for the reader to understand how the code is building up. But at the same time, they can also edit the code for any step. I'll remove the highlights on any code change, for now, to keep things simple. There'll also be a reset button that will reset the code to the original and bring back the highlights. There will be more users just skimming through the page or following the tutorial locally than those actually editing, where the diff highlight would be very useful.
