### ISSUE TITLE
how to get activeFile language ?

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [codesandbox/sandpack#669]
# Tell us how you think we can improve Sandpack

i can get the files info, but without language,
```tsx
...
const { sandpack } = useSandpack();
...
console.info(sandpack.files)
...
```
![image](https://user-images.githubusercontent.com/104620424/208022695-c164f01d-aea3-4f56-9aed-a69af1e264da.png)

i hope we can add a `language` filed to the `SandpackBundlerFile`
```tsx
//@codesandbox/sandpack-client/dist/types/types.d.ts

export interface SandpackBundlerFile {
    code: string;
    hidden?: boolean;
    active?: boolean;
    readOnly?: boolean;
    language?: string // e.g: javascript, html, css, react
}
```

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## What is this feature?
add a `language` filed to the `SandpackBundlerFile`

## How would your idea work?
then i can use `sandpack.files[sandpack.activeFile].language` get the code language

## Do you have any examples of how you would like to see us implement it?

no

**Comment by danilowoz** [comment]
Hey, thanks for opening this issue!

By this time, we don't want to introduce one more key to `SandpackBundlerFile` because this type is tied to Sandpack Client, which is supposed to be agnostic and generic. Also, the mechanism to find out the file language depends on Codemirror (which is a Sandpack React dependency) - in other words, we don't want to cross dependencies through scopes.

However, as mentioned before, Sandpack React has the util to find out the language for a given file. Would it help you if we could expose this `util`? It would work like this:

```
const languageExtension = getLanguageFromFile(filePath);
```

**Comment by hu-tu-yi-shi** [comment]
thank you
this is my code ，i hope it can help other people:

```tsx
type TLanguage = {
  [key: string]: string;
};

const languageEnum: TLanguage = {
  js: "javascript",
  html: "html",
  css: "css",
  ts: "typescript",
};

... 

const fileExtension = sandpack.activeFile.split(".").pop() ?? "js";
const theLanguage = languageEnum[fileExtension];
 

````

**Comment by danilowoz** [comment]
I think we can use this piece of code:

https://github.com/codesandbox/sandpack/blob/draft/quiet-dust/sandpack-react/src/components/CodeEditor/utils.ts#L156-L196
```js
switch (extension) {
    case "ts":
    case "tsx":
      return "typescript";
    case "html":
    case "svelte":
    case "vue":
      return "html";
    case "css":
    case "less":
    case "scss":
      return "css";
    case "js":
    case "jsx":
    case "json":
    default:
      return "javascript";
  }
```

**Comment by hu-tu-yi-shi** [comment]
thank you  very much  , your code is better than me
