### ISSUE TITLE
Sandpack and Codesandbox rendering the same code differently

### ISSUE THREAD

**Issue by vipulbhj** [codesandbox/sandpack#68]
Hey, I was playing around with `Sandpack-React` and noticed some differences in how codesandbox and sandpack render the same code. 

Here is the link of the codesandbox demo that I built. [https://codesandbox.io/s/sandpack-codesandbox-rendering-conflict-fry37?file=/src/App.js](DEMO)

Here is my simple component, it uses `react-native-web`, when I use this in `codesandbox` I get the expected behaviour of `flex: 1` covering the whole screen height.

```js
function Original() {
  return (
    <View
      style={{
        backgroundColor: "orangered",
        flex: 1
      }}
    >
      <Text
        style={{
          color: "white",
          fontSize: 64,
          padding: 5
        }}
      >
        React Native Text
      </Text>
    </View>
  );
}
```

But when I use the same code in `Sandpack` setting, it only takes the height which is equal to the height of content. 

```js
const code = `
import React from "react";
import { View, Text } from "react-native";

function App() {
  return (
    <View
      style={{
        backgroundColor: "orangered",
        flex: 1
      }}
    >
      <Text
        style={{
          color: "white",
          fontSize: 64,
          padding: 5
        }}
      >
        React Native Text
      </Text>
    </View>
  );
}

export default App;
`;


<Sandpack
  template="react"
  files={{
    "/App.js": code
  }}
  customSetup={{
    dependencies: {
      "react-native-web": "latest"
    }
  }}
/>
```

The video below shows a screen capture of the codesandbox demo mentioned above.

https://user-images.githubusercontent.com/33618798/121869568-ce138c80-cd1f-11eb-87ff-e04ee62debaa.mov

Any ideas on how we can fix this issue ?

**Comment by alexnm** [comment]
The issues is that the html/body/root elements don't get some inline style applied to them (to make them full height and the root display: flex)

I see you have an inline style tag in your `index.html` entry file in codesandbox. There are two issues here:

1. You need to pass that custom html file to sandpack as well. Otherwise it will use the default index.html from create-react-app which does not contain the styling for the html/body/root elements.
2. Even if you pass that html, unfortunately this will not work for the moment, as we have a bug #32 in sandpack, because of the way in which the bundler constructs the index.html page. CodeSandbox uses a custom bundler server, so we can change that html file, whereas Sandpack uses a static version, so we're working on a solution that can fix this inside this static bundler.

**Comment by vipulbhj** [comment]
Thanks for all your help @alexnm 

Will be following this closely on when can we do this and in the meantime will try to use some workaround :)
