### ISSUE TITLE
Open in New Window

### ISSUE THREAD

**Issue by rebeccapeltz** [codesandbox/sandpack#701]
# Tell us how you think we can improve Sandpack

The "Open in New Window" button found on codesandbox.io is really helpful for doing good inspections, like network activity, with your code.  Is there a way to do this in Sandpack?  If not, this would be a very useful feature.

## Packages affected

-   [ ] sandpack-client
-   [ x] sandpack-react

## How would your idea work?
This could be an option included in the options object: showOpenInNewTabButton=false (false by default)

## Do you have any examples of how you would like to see us implement it?
It could be implemented similarly to the navigator refresh, only opening in a new tab

**Comment by rebeccapeltz** [comment]
Note that the work around is to open the Sandpack in codesandbox.io by clicking on the "Open in Codesandbox" and then clicking on the "Open in new window button" from there.

**Comment by danilowoz** [comment]
Unfortunately, Sandpack can't open the same preview on another tab. There are some significant differences between CodeSandbox preview (which is hosted on a server) and Sandpack (which static bundler files on the browser window).  

In order to make it happen, we would be a completely new architecture on Sandpack, which is not on our plans right now.
