### ISSUE TITLE
Documentation: 

### ISSUE THREAD

**Issue by atakndogn** [codesandbox/sandpack#764]
Hi, I see the following problem in beta React tutorial pages, e.g from https://beta.reactjs.org/learn/render-and-commit.
I currently solve this problem by forking the example on the new tab but on the page it does give the following error: 

"Unable to establish connection with the sandpack bundler. Make sure you are online or try again later. If the problem persists, please report it via [email](mailto:hello@codesandbox.io?subject=Sandpack%20Timeout%20Error) or submit an issue on [GitHub.](https://github.com/codesandbox/sandpack/issues)"

<img width="1440" alt="Screenshot 2023-02-25 at 11 28 45" src="https://user-images.githubusercontent.com/52030014/221347317-e03540c9-6626-493c-8737-c909bff32e31.png">

FYI

**Comment by danilowoz** [comment]
Hey! Thanks for reporting this issue. 

Are you still facing this issue? I can't reproduce it, so that we might've faced an instability on our CDN, but it looks good now. 
<img width="995" alt="Screenshot 2023-02-27 at 21 16 30" src="https://user-images.githubusercontent.com/4838076/221687472-47258aa0-6552-4f15-a149-406b03290bf8.png">
