### ISSUE TITLE
Custom files without using Sandpack 

### ISSUE THREAD

**Issue by GeorgeDimCeid** [codesandbox/sandpack#78]
Trying to follow the example 
``` import {
  SandpackProvider,
  SandpackLayout,
  SandpackCodeEditor,
  SandpackPreview,
} from "@codesandbox/sandpack-react";

const CustomSandpack = () => (
  <SandpackProvider template="react">
    <SandpackLayout>
      <SandpackCodeEditor />
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);
```
I was't able to find a way to insert custom files to the initiated sandbox and could not find an example on docs.
Is there a way of   initiate the sandbox with my custom files while using this setup?

**Comment by danilowoz** [comment]
Hey @GeorgeDimCeid, thanks for opening this issue. We know that our documentation still is not that good, and we're looking forward to improving it. That's why it's so important to know when you don't find in the documentation what you're looking for.

So basically, you can use the `customSetup` prop which is a `SandpackSetup` type that supports the files options.

```jsx
const CustomSandpack = () => (
  <SandpackProvider 
    template="react" 
    customSetup={{
        files: {
            "/App.js": code,
        },
    }}>
    <SandpackLayout>
      <SandpackCodeEditor />
      <SandpackPreview />
    </SandpackLayout>
  </SandpackProvider>
);
```

**Comment by GeorgeDimCeid** [comment]
I was wondering if you can pass your whole project folder or to be shown inside the sandpack instance via the files prop 
![image](https://user-images.githubusercontent.com/66006700/129064754-f7532229-0215-4ce8-9e64-88a5f4a1ec93.png)
can anyone show me an example?
