### ISSUE TITLE
Local files to sandpack

### ISSUE THREAD

**Issue by GeorgeDimCeid** [codesandbox/sandpack#82]
I was wondering if you can pass your whole project folder or file  to be shown inside the sandpack instance via the files prop 
![image](https://user-images.githubusercontent.com/66006700/129064754-f7532229-0215-4ce8-9e64-88a5f4a1ec93.png)
can anyone show me an example?

**Comment by danilowoz** [comment]
Hey @GeorgeDimCeid
Yes, we can import local files to the Sandpack, as you can check out here http://localhost:3000/s/import-local-files-djbzp?file=/src/App.js, basically, it uses the `raw-loader` from webpack to get the content file. However, I couldn't find out a way to import the entire folder and make it work in a browser environment, because it would require dynamically load the modules, maybe you can do it using the `fs` module from `node`, like this:

```js
const testFolder = './tests/';
const fs = require('fs');

fs.readdir(testFolder, (err, files) => {
  files.forEach(file => {
    // load file and pass to Sandpack
    console.log(file);
  });
})
```
