### ISSUE TITLE
Project works in CodeSandbox, not in sandpack

### ISSUE THREAD

**Issue by CharcoalStyles** [codesandbox/sandpack#83]
I've got a basic HMTL/CSS/JS demo. It imports a library in the HMTL file.

When running the code in sandpack, the JS errors saying the imported library is not present. But when loading codesandbox, the project works fine.

[Here is the project, in codesandbox](https://codesandbox.io/s/fowfq?from-sandpack=true)

Any help would be appreciated!

**Comment by danilowoz** [comment]
Hey @CharcoalStyles, sorry for hearing you've been facing some problems in the Sandpack. But fortunately, I made your sandbox works in the Sandpack 🎉 !

You can check it in this Sandpack https://codesandbox.io/s/mapbox-dependency-wzccy?file=/src/App.js

---

**Why didn't it work in the first place?** Unfortunately, we still have some issues when the template tries to load `script` and `link` tags in the head, which were your case, more here in #44. So in order to manage this, I added the mapbox as a dependency in the Sandpack component:

```diff
      <Sandpack
        template="vanilla"
        customSetup={{
          entry: "index.html",
          dependencies: {
++          "mapbox-gl": "latest"
          }
        }}
        files={{
          "/src/index.js": indexJs,
          "/src/style.css": style,
          "/index.html": indexHtml
        }}
      />
```

**Comment by CharcoalStyles** [comment]
@danilowoz thanks for the help; I'll be watching #44 closely.

I've used the import of `mapbox-gl` in another sandpack, but I've got a tutorial that is basic HTML/CSS/JS and I want to have a Sandpack at the end showing all the files in a working demo.
Using the dependencies means adding imports at the start of the JS file, which might confuse some people.
