### ISSUE TITLE
/index.js: Could not find module in path: 'react-dom/client' relative to '/index.js'

### ISSUE THREAD

**Issue by xiaohehennuli** [codesandbox/sandpack#911]
# Bug report
My component library dependency is React 17, but after installing React 17, Sandpack keeps giving me the error "/index.js: Could not find module in path: 'react-dom/client' relative to '/index.js'", how to solve it?

## Packages affected

-   [ ] sandpack-client
-   [ ✅] sandpack-react

## Description of the problem
My component library dependency is React 17, but after installing React 17, Sandpack keeps giving me the error "/index.js: Could not find module in path: 'react-dom/client' relative to '/index.js'", how to solve it?

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-client version |              |
| Sandpack-react version  |       1.19.0       |
| Browser                 |      chrome        |
| Operating System        |          mac    |

![image](https://user-images.githubusercontent.com/48360574/233340667-8a88910f-4e60-492b-b803-3cda7b677f51.png)
![image](https://user-images.githubusercontent.com/48360574/233340948-2b169b58-c9f3-4377-be61-4d01a4b19a39.png)

**Comment by SSHari** [comment]
@xiaohehennuli The problem you're running into is that `createRoot` was [released in React 18](https://github.com/facebook/react/releases/tag/v18.0.0). This is the default version of React that's installed when you use the `react` Sandpack template. Since Sandpack is expecting React 18, it's using the newer syntax in the `/index.js` file that's automatically created.

In your case, you're explicitly installing React 17 which doesn't have the `createRoot` export. This is causing the Sandpack `/index.js` file to throw that error you're seeing.

To get around this you can change the `/index.js` file that's passed to the Sandpack instance so that it uses the older syntax. Here's a Code Sandbox example that shows you how you can do that: https://codesandbox.io/s/condescending-nash-108pv1?file=/src/App.tsx.

I left some comments in the custom `/index.js` file that outlines what parts require React 18.

**Comment by xiaohehennuli** [comment]
Thank you for your help. I have successfully solved the problem.
